name: Deploy to EB
# main branch에 push 되면 실행
on:
  push:
    branches:
      - main

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-18.04
    strategy:
      # Node version은 12 버전을 이용한다.
      matrix:
        node-version: ["12.x"]

    steps:
      - uses: actions/checkout@v2

      # Initialize Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Install project dependencies, test and build
      - name: Install dependencies
        run: npm install

